### ISSUE TITLE
call for code 

### ISSUE THREAD

**Issue by xiyufeng2** [zju3dv/IntrinsicNeRF#1]
Hello，I am interested in your work. Can you share your code with me? My email xiyufeng1@gmail.com. Thank you for your reply

**Comment by Jerrypiglet** [comment]
Same issues here. It would be great to have the full code released given the paper is accepted to ICCV (and congrats!)

**Comment by ywcmaike** [comment]
Thanks for your interest. We're so sorry to release the code late. We are refactoring and cleaning the code now (It may be ready before the ICCV conference because we are preparing the submissions for ICLR/CVPR2024).

**Comment by ywcmaike** [comment]
The code was released last week.
